### ISSUE TITLE
MUSICO select conciertos ya asignados

### ISSUE THREAD

**Issue by amcgamer** [amcgamer/Find-your-concert#11]
select us.nombre_artista_grupo_local_fan, po.nombre_poblacion, us.direccion1, co.fecha, co.hora, co.precio, ge.nombre_genero
from conciertos co
inner join usuarios us on us.correo_electronico = co.id_local
inner join genero ge on ge.id_genero = co.id_genero
inner join poblacion po on po.id_poblacion = us.poblacion_id_poblacion
inner join apuntar ap on ap.id_conciertos = co.id_conciertos
where ap.estado = 'c' and ap.usuarios_correo_electronico = '$correo_musico'

**Comment by gian30** [comment]
fet
